        db      41h              ; WILF (right part) welcome text
        db      3eh
        db      40h
        db      7eh
        db      41h
        db      08h
        db      40h
        db      42h
        db      41h
        db      08h
        db      40h
        db      40h
        db      41h
        db      08h
        db      40h
        db      48h
        db      49h
        db      08h
        db      40h
        db      78h
        db      55h
        db      08h
        db      40h
        db      48h
        db      63h
        db      08h
        db      42h
        db      40h
        db      41h
        db      3eh
        db      7eh
        db      40h
