        db      41h              ; KOKOTONI (left part) welcome text
        db      3ch
        db      41h
        db      3ch
        db      7fh
        db      3ch
        db      41h
        db      3eh
        db      42h
        db      42h
        db      42h
        db      42h
        db      49h
        db      42h
        db      61h
        db      08h
        db      44h
        db      81h
        db      44h
        db      81h
        db      08h
        db      81h
        db      51h
        db      08h
        db      48h
        db      81h
        db      48h
        db      81h
        db      08h
        db      81h
        db      49h
        db      08h
        db      70h
        db      81h
        db      70h
        db      81h
        db      08h
        db      81h
        db      49h
        db      08h
        db      48h
        db      81h
        db      48h
        db      81h
        db      08h
        db      81h
        db      45h
        db      08h
        db      44h
        db      42h
        db      44h
        db      42h
        db      08h
        db      42h
        db      43h
        db      08h
        db      42h
        db      3ch
        db      42h
        db      3ch
        db      08h
        db      3ch
        db      41h
        db      3eh
        db      00h
