        db      00h              ; sprites
        db      00h
        db      01h
        db      0c0h
        db      07h
        db      0e0h
        db      3fh
        db      0f0h
        db      7fh
        db      90h
        db      0ffh
        db      7ch
        db      0feh
        db      0feh
        db      7eh
        db      0feh
        db      2fh
        db      0eeh
        db      77h
        db      0ech
        db      7bh
        db      9ch
        db      3fh
        db      0f8h
        db      1ch
        db      78h
        db      00h
        db      30h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0fh
        db      00h
        db      3fh
        db      0c0h
        db      73h
        db      0f0h
        db      7fh
        db      0fch
        db      5fh
        db      0ffh
        db      3fh
        db      0ffh
        db      1fh
        db      0ffh
        db      01h
        db      0ffh
        db      03h
        db      0ffh
        db      07h
        db      1fh
        db      00h
        db      07h
        db      00h
        db      01h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0fh
        db      00h
        db      3fh
        db      0e0h
        db      73h
        db      0fch
        db      7fh
        db      0ffh
        db      5fh
        db      0ffh
        db      3fh
        db      0ffh
        db      1fh
        db      0ffh
        db      01h
        db      0ffh
        db      07h
        db      0ffh
        db      03h
        db      1fh
        db      00h
        db      03h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0fh
        db      00h
        db      3fh
        db      0f0h
        db      73h
        db      0ffh
        db      7fh
        db      0ffh
        db      5fh
        db      0ffh
        db      3fh
        db      0ffh
        db      1fh
        db      0ffh
        db      01h
        db      0ffh
        db      07h
        db      0ffh
        db      03h
        db      87h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      04h
        db      80h
        db      0ch
        db      0c0h
        db      18h
        db      0e0h
        db      38h
        db      0f8h
        db      0f0h
        db      0ffh
        db      0f0h
        db      0ffh
        db      0e0h
        db      0ffh
        db      0c0h
        db      0ffh
        db      80h
        db      3eh
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      80h
        db      04h
        db      0c0h
        db      0ch
        db      0e0h
        db      18h
        db      0f8h
        db      78h
        db      0ffh
        db      0f0h
        db      0ffh
        db      0f0h
        db      0ffh
        db      0e0h
        db      0ffh
        db      0c0h
        db      3fh
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      80h
        db      00h
        db      0c0h
        db      04h
        db      0e0h
        db      0ch
        db      0f8h
        db      18h
        db      0fch
        db      78h
        db      0ffh
        db      0f0h
        db      0ffh
        db      0f0h
        db      0ffh
        db      0e0h
        db      7fh
        db      0c0h
        db      1fh
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      02h
        db      00h
        db      04h
        db      00h
        db      09h
        db      0c0h
        db      17h
        db      0e0h
        db      3eh
        db      0f8h
        db      45h
        db      60h
        db      83h
        db      80h
        db      07h
        db      00h
        db      0eh
        db      00h
        db      07h
        db      00h
        db      03h
        db      00h
        db      01h
        db      80h
        db      00h
        db      0c0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      02h
        db      00h
        db      04h
        db      00h
        db      09h
        db      0c0h
        db      17h
        db      0e0h
        db      3eh
        db      0f8h
        db      45h
        db      60h
        db      83h
        db      80h
        db      07h
        db      00h
        db      03h
        db      80h
        db      00h
        db      0c0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      30h
        db      02h
        db      0e0h
        db      07h
        db      0c0h
        db      09h
        db      0c0h
        db      16h
        db      0a0h
        db      3fh
        db      78h
        db      47h
        db      0e0h
        db      81h
        db      0c0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      30h
        db      00h
        db      60h
        db      00h
        db      0c0h
        db      03h
        db      0c0h
        db      07h
        db      80h
        db      09h
        db      0c0h
        db      16h
        db      0a0h
        db      3fh
        db      78h
        db      47h
        db      0e0h
        db      81h
        db      0c0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      03h
        db      0cch
        db      0fh
        db      0eah
        db      9fh
        db      0bfh
        db      0fbh
        db      7fh
        db      7dh
        db      7ch
        db      1dh
        db      0f2h
        db      0ah
        db      50h
        db      0dh
        db      68h
        db      03h
        db      0cch
        db      0fh
        db      0eah
        db      9fh
        db      0ffh
        db      0fdh
        db      7fh
        db      7dh
        db      7eh
        db      1bh
        db      0d0h
        db      14h
        db      68h
        db      0ah
        db      14h
        db      03h
        db      80h
        db      0eh
        db      40h
        db      9dh
        db      0e0h
        db      0fah
        db      0e0h
        db      7bh
        db      0e0h
        db      1ch
        db      40h
        db      0ah
        db      0a0h
        db      0dh
        db      50h
        db      01h
        db      0c0h
        db      03h
        db      0e0h
        db      05h
        db      0fah
        db      0fh
        db      0deh
        db      0fh
        db      0bch
        db      03h
        db      0b8h
        db      05h
        db      50h
        db      0ah
        db      0b0h
        db      33h
        db      0c0h
        db      57h
        db      0f0h
        db      0fdh
        db      0f9h
        db      0feh
        db      0dfh
        db      3eh
        db      0beh
        db      4fh
        db      0b8h
        db      0ah
        db      50h
        db      16h
        db      0b0h
        db      33h
        db      0c0h
        db      57h
        db      0f0h
        db      0ffh
        db      0f9h
        db      0feh
        db      0bfh
        db      7eh
        db      0beh
        db      0bh
        db      0d8h
        db      16h
        db      28h
        db      28h
        db      50h
        db      01h
        db      0c0h
        db      02h
        db      70h
        db      07h
        db      0b9h
        db      07h
        db      5fh
        db      07h
        db      0deh
        db      02h
        db      38h
        db      05h
        db      50h
        db      0ah
        db      0b0h
        db      03h
        db      80h
        db      07h
        db      0c0h
        db      5fh
        db      0a0h
        db      7bh
        db      0f0h
        db      3dh
        db      0f0h
        db      1dh
        db      0c0h
        db      0ah
        db      0a0h
        db      0dh
        db      50h
        db      22h
        db      44h
        db      71h
        db      8eh
        db      7dh
        db      0beh
        db      0feh
        db      7fh
        db      0ffh
        db      0ffh
        db      0ffh
        db      0ffh
        db      3fh
        db      0fch
        db      1fh
        db      0f8h
        db      07h
        db      0e0h
        db      03h
        db      0c0h
        db      02h
        db      40h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      02h
        db      40h
        db      09h
        db      90h
        db      1dh
        db      0b8h
        db      1eh
        db      78h
        db      3fh
        db      0fch
        db      3fh
        db      0fch
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      02h
        db      40h
        db      09h
        db      90h
        db      1dh
        db      0b8h
        db      1eh
        db      78h
        db      3fh
        db      0fch
        db      3fh
        db      0fch
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      6fh
        db      0f6h
        db      43h
        db      0c2h
        db      02h
        db      40h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      02h
        db      40h
        db      01h
        db      80h
        db      05h
        db      0a0h
        db      0eh
        db      70h
        db      1fh
        db      0f8h
        db      1fh
        db      0f8h
        db      3fh
        db      0fch
        db      3fh
        db      0fch
        db      3fh
        db      0fch
        db      3bh
        db      0dch
        db      1ah
        db      58h
        db      18h
        db      18h
        db      0ch
        db      30h
        db      04h
        db      20h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      02h
        db      00h
        db      01h
        db      00h
        db      01h
        db      84h
        db      21h
        db      84h
        db      11h
        db      4ch
        db      1bh
        db      5eh
        db      1bh
        db      7ah
        db      3eh
        db      0f6h
        db      2eh
        db      0f6h
        db      2eh
        db      0ech
        db      36h
        db      0d8h
        db      17h
        db      0b8h
        db      0dh
        db      60h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      20h
        db      00h
        db      20h
        db      08h
        db      30h
        db      08h
        db      70h
        db      0ch
        db      50h
        db      0ch
        db      0d0h
        db      1ah
        db      0f2h
        db      1bh
        db      0b4h
        db      35h
        db      6eh
        db      35h
        db      7eh
        db      36h
        db      0f6h
        db      36h
        db      0ech
        db      1ah
        db      0d8h
        db      0fh
        db      0f0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      02h
        db      40h
        db      01h
        db      80h
        db      03h
        db      40h
        db      05h
        db      0e0h
        db      0fh
        db      50h
        db      0bh
        db      0f0h
        db      0fh
        db      50h
        db      07h
        db      0e0h
        db      05h
        db      0e0h
        db      33h
        db      4ch
        db      0f9h
        db      9eh
        db      6fh
        db      0f3h
        db      07h
        db      0e0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      30h
        db      06h
        db      38h
        db      0eh
        db      2ch
        db      1ah
        db      3eh
        db      1eh
        db      1ah
        db      2ch
        db      0fh
        db      70h
        db      33h
        db      6ch
        db      0f9h
        db      0deh
        db      6fh
        db      0f3h
        db      07h
        db      0e0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      1ch
        db      38h
        db      3fh
        db      0fch
        db      43h
        db      0c2h
        db      81h
        db      81h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      78h
        db      1eh
        db      8ch
        db      31h
        db      03h
        db      0c0h
        db      01h
        db      80h
        db      01h
        db      80h
        db      00h
        db      00h
        db      00h
        db      10h
        db      00h
        db      00h
        db      0ch
        db      00h
        db      80h
        db      0ffh
        db      0c0h
        db      67h
        db      0fah
        db      0b8h
        db      3fh
        db      0f5h
        db      0fch
        db      1fh
        db      0f5h
        db      0f8h
        db      33h
        db      0fah
        db      0e0h
        db      0c0h
        db      3fh
        db      00h
        db      00h
        db      08h
        db      00h
        db      00h
        db      1ch
        db      00h
        db      80h
        db      0e6h
        db      00h
        db      67h
        db      9bh
        db      00h
        db      3fh
        db      7fh
        db      00h
        db      1fh
        db      0bfh
        db      00h
        db      33h
        db      0c7h
        db      00h
        db      0c0h
        db      3eh
        db      00h
        db      00h
        db      04h
        db      0c0h
        db      00h
        db      1dh
        db      80h
        db      00h
        db      0ffh
        db      80h
        db      03h
        db      5fh
        db      00h
        db      07h
        db      0efh
        db      80h
        db      03h
        db      0edh
        db      80h
        db      01h
        db      0dah
        db      0e0h
        db      00h
        db      7ch
        db      40h
        db      00h
        db      08h
        db      00h
        db      00h
        db      30h
        db      00h
        db      03h
        db      0ffh
        db      01h
        db      1dh
        db      5fh
        db      0e6h
        db      3fh
        db      0afh
        db      0fch
        db      1fh
        db      0afh
        db      0f8h
        db      07h
        db      5fh
        db      0cch
        db      00h
        db      0fch
        db      03h
        db      00h
        db      10h
        db      00h
        db      00h
        db      38h
        db      00h
        db      00h
        db      67h
        db      01h
        db      00h
        db      0d9h
        db      0e6h
        db      00h
        db      0feh
        db      0fch
        db      00h
        db      0fdh
        db      0f8h
        db      00h
        db      0e3h
        db      0cch
        db      00h
        db      7ch
        db      03h
        db      03h
        db      20h
        db      00h
        db      01h
        db      0b8h
        db      00h
        db      01h
        db      0ffh
        db      00h
        db      00h
        db      0fah
        db      0c0h
        db      01h
        db      0f7h
        db      0e0h
        db      01h
        db      0b7h
        db      0c0h
        db      07h
        db      5bh
        db      80h
        db      02h
        db      3eh
        db      00h
        db      00h
        db      00h
        db      01h
        db      0c0h
        db      03h
        db      0e0h
        db      37h
        db      0e1h
        db      4fh
        db      0f2h
        db      85h
        db      6ch
        db      1fh
        db      0e0h
        db      27h
        db      0e4h
        db      0cbh
        db      0dah
        db      13h
        db      31h
        db      24h
        db      88h
        db      24h
        db      84h
        db      44h
        db      42h
        db      48h
        db      22h
        db      10h
        db      24h
        db      08h
        db      40h
        db      0ch
        db      00h
        db      11h
        db      0c0h
        db      0a3h
        db      0e0h
        db      97h
        db      0e0h
        db      4fh
        db      0e0h
        db      37h
        db      0f0h
        db      0dh
        db      69h
        db      67h
        db      0e6h
        db      9bh
        db      0d0h
        db      86h
        db      0cch
        db      19h
        db      22h
        db      22h
        db      42h
        db      42h
        db      41h
        db      41h
        db      30h
        db      80h
        db      88h
        db      00h
        db      64h
        db      0ch
        db      00h
        db      16h
        db      00h
        db      1fh
        db      00h
        db      07h
        db      00h
        db      0fh
        db      80h
        db      03h
        db      80h
        db      05h
        db      0c0h
        db      0bh
        db      0c0h
        db      02h
        db      0e0h
        db      07h
        db      0e0h
        db      07h
        db      0f0h
        db      07h
        db      0f0h
        db      07h
        db      0b8h
        db      03h
        db      5ch
        db      03h
        db      46h
        db      06h
        db      80h
        db      0ch
        db      00h
        db      16h
        db      00h
        db      1fh
        db      00h
        db      07h
        db      00h
        db      0fh
        db      80h
        db      03h
        db      80h
        db      05h
        db      0c0h
        db      0bh
        db      0c0h
        db      02h
        db      0e0h
        db      07h
        db      0e0h
        db      0fh
        db      0f0h
        db      0fh
        db      0f0h
        db      0fh
        db      38h
        db      06h
        db      0dch
        db      06h
        db      0c6h
        db      0dh
        db      80h
        db      0ch
        db      00h
        db      16h
        db      00h
        db      1fh
        db      00h
        db      07h
        db      00h
        db      0fh
        db      80h
        db      03h
        db      80h
        db      05h
        db      0c0h
        db      0bh
        db      0c0h
        db      02h
        db      0e0h
        db      07h
        db      0e0h
        db      07h
        db      0f0h
        db      07h
        db      0f0h
        db      03h
        db      0b8h
        db      05h
        db      0dch
        db      06h
        db      0c6h
        db      0dh
        db      80h
        db      03h
        db      0c0h
        db      0fh
        db      0f0h
        db      1fh
        db      0b8h
        db      3bh
        db      0fch
        db      77h
        db      0f6h
        db      7fh
        db      0feh
        db      0feh
        db      7bh
        db      0fdh
        db      0bfh
        db      0fdh
        db      0bfh
        db      0eeh
        db      7fh
        db      7fh
        db      0feh
        db      7fh
        db      0eeh
        db      3fh
        db      0dch
        db      1ch
        db      78h
        db      0fh
        db      0f0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      0fh
        db      0f0h
        db      1fh
        db      0f8h
        db      3dh
        db      0fch
        db      7fh
        db      0eeh
        db      7fh
        db      0f6h
        db      0deh
        db      7fh
        db      0ddh
        db      0bfh
        db      0ddh
        db      0bfh
        db      0feh
        db      7fh
        db      6fh
        db      0f6h
        db      77h
        db      0feh
        db      3fh
        db      0dch
        db      1fh
        db      78h
        db      0fh
        db      0f0h
        db      03h
        db      0c0h
        db      60h
        db      30h
        db      38h
        db      38h
        db      3ch
        db      7ch
        db      0feh
        db      00h
        db      06h
        db      0ch
        db      1ch
        db      1ch
        db      3ch
        db      3eh
        db      7fh
        db      00h
        db      3ch
        db      7ah
        db      0fdh
        db      0fdh
        db      0ffh
        db      0ffh
        db      7eh
        db      3ch
        db      01h
        db      10h
        db      03h
        db      88h
        db      03h
        db      08h
        db      02h
        db      44h
        db      01h
        db      84h
        db      02h
        db      44h
        db      07h
        db      0eah
        db      07h
        db      0dah
        db      02h
        db      84h
        db      03h
        db      0c4h
        db      01h
        db      0c4h
        db      02h
        db      0e8h
        db      02h
        db      0e8h
        db      0eh
        db      0f0h
        db      1fh
        db      60h
        db      17h
        db      30h
        db      01h
        db      20h
        db      03h
        db      90h
        db      03h
        db      08h
        db      02h
        db      48h
        db      01h
        db      84h
        db      06h
        db      44h
        db      0fh
        db      0eah
        db      0fh
        db      0dah
        db      05h
        db      44h
        db      03h
        db      0c4h
        db      01h
        db      0c8h
        db      02h
        db      0e8h
        db      02h
        db      0f0h
        db      0eh
        db      0e0h
        db      1fh
        db      60h
        db      17h
        db      30h
        db      00h
        db      00h
        db      62h
        db      0ffh
        db      62h
        db      00h
        db      00h
        db      00h
        db      40h
        db      0e0h
        db      60h
        db      10h
        db      0ah
        db      06h
        db      0eh
        db      00h
        db      54h
        db      40h
        db      39h
        db      0c0h
        db      33h
        db      0c0h
        db      25h
        db      40h
        db      11h
        db      00h
        db      39h
        db      00h
        db      7dh
        db      00h
        db      5eh
        db      00h
        db      5dh
        db      00h
        db      68h
        db      00h
        db      38h
        db      00h
        db      28h
        db      00h
        db      28h
        db      00h
        db      28h
        db      00h
        db      28h
        db      00h
        db      34h
        db      00h
        db      54h
        db      00h
        db      38h
        db      0a0h
        db      30h
        db      60h
        db      24h
        db      78h
        db      10h
        db      0b0h
        db      38h
        db      0a0h
        db      7dh
        db      00h
        db      5eh
        db      00h
        db      5dh
        db      00h
        db      68h
        db      00h
        db      38h
        db      00h
        db      28h
        db      00h
        db      24h
        db      00h
        db      44h
        db      00h
        db      44h
        db      00h
        db      22h
        db      00h
        db      54h
        db      00h
        db      38h
        db      00h
        db      30h
        db      50h
        db      24h
        db      20h
        db      10h
        db      78h
        db      38h
        db      0b0h
        db      7dh
        db      20h
        db      5eh
        db      00h
        db      5dh
        db      00h
        db      68h
        db      00h
        db      38h
        db      00h
        db      28h
        db      00h
        db      44h
        db      00h
        db      44h
        db      00h
        db      82h
        db      00h
        db      43h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      43h
        db      00h
        db      0a7h
        db      0c4h
        db      0fch
        db      0f8h
        db      38h
        db      30h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      58h
        db      70h
        db      0bch
        db      0f8h
        db      0f7h
        db      0cdh
        db      03h
        db      86h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0c2h
        db      23h
        db      0e5h
        db      1fh
        db      3fh
        db      0ch
        db      1ch
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0eh
        db      1ah
        db      1fh
        db      3dh
        db      0b3h
        db      0efh
        db      61h
        db      0c0h
        db      00h
        db      0e0h
        db      01h
        db      0d0h
        db      03h
        db      0d0h
        db      03h
        db      0d0h
        db      06h
        db      0e0h
        db      05h
        db      0f0h
        db      01h
        db      0fch
        db      03h
        db      0bch
        db      03h
        db      0dch
        db      07h
        db      0ech
        db      07h
        db      0e4h
        db      08h
        db      10h
        db      0eh
        db      70h
        db      0eh
        db      0b0h
        db      1dh
        db      0b8h
        db      1fh
        db      0f8h
        db      00h
        db      60h
        db      00h
        db      0d0h
        db      01h
        db      90h
        db      01h
        db      0d0h
        db      02h
        db      0e0h
        db      01h
        db      0f0h
        db      01h
        db      0d8h
        db      01h
        db      6ch
        db      03h
        db      0b4h
        db      03h
        db      0bch
        db      03h
        db      0d8h
        db      04h
        db      10h
        db      04h
        db      0f0h
        db      02h
        db      0f8h
        db      0bh
        db      78h
        db      0fh
        db      0f8h
        db      00h
        db      0c0h
        db      01h
        db      0e0h
        db      01h
        db      20h
        db      01h
        db      20h
        db      00h
        db      0c0h
        db      01h
        db      0e0h
        db      03h
        db      0f0h
        db      07h
        db      0f8h
        db      0eh
        db      0bch
        db      0eh
        db      0d8h
        db      05h
        db      0e8h
        db      03h
        db      0f0h
        db      00h
        db      00h
        db      05h
        db      0f0h
        db      07h
        db      0f8h
        db      0fh
        db      0f8h
        db      07h
        db      00h
        db      0bh
        db      80h
        db      0bh
        db      0c0h
        db      0bh
        db      0c0h
        db      07h
        db      60h
        db      0fh
        db      0a0h
        db      3fh
        db      80h
        db      3dh
        db      0c0h
        db      3bh
        db      0c0h
        db      37h
        db      0e0h
        db      27h
        db      0e0h
        db      08h
        db      10h
        db      0fh
        db      0f0h
        db      0fh
        db      0f0h
        db      1fh
        db      0f8h
        db      1fh
        db      0f8h
        db      06h
        db      00h
        db      0bh
        db      00h
        db      09h
        db      80h
        db      0bh
        db      80h
        db      07h
        db      40h
        db      0fh
        db      80h
        db      1bh
        db      80h
        db      36h
        db      80h
        db      2dh
        db      0c0h
        db      3dh
        db      0c0h
        db      1bh
        db      0c0h
        db      08h
        db      20h
        db      0fh
        db      0e0h
        db      1fh
        db      0e0h
        db      1fh
        db      0f0h
        db      1fh
        db      0f0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      03h
        db      0feh
        db      06h
        db      66h
        db      0fh
        db      0fch
        db      18h
        db      34h
        db      3fh
        db      0eah
        db      7fh
        db      0c2h
        db      0c0h
        db      54h
        db      0b0h
        db      0a8h
        db      86h
        db      90h
        db      0c0h
        db      60h
        db      7fh
        db      0c0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      18h
        db      00h
        db      68h
        db      01h
        db      88h
        db      02h
        db      10h
        db      06h
        db      60h
        db      09h
        db      80h
        db      13h
        db      0fch
        db      27h
        db      0fah
        db      4fh
        db      0f2h
        db      0dfh
        db      0e4h
        db      0bfh
        db      0c8h
        db      80h
        db      50h
        db      0c0h
        db      60h
        db      7fh
        db      0c0h
        db      0ffh
        db      0ffh
        db      52h
        db      4ah
        db      3fh
        db      0fch
        db      3fh
        db      0cch
        db      77h
        db      0e6h
        db      7fh
        db      0f2h
        db      0dfh
        db      0f3h
        db      0ffh
        db      0f3h
        db      0ffh
        db      0ffh
        db      0dfh
        db      0ffh
        db      0ffh
        db      0ffh
        db      7fh
        db      0feh
        db      6fh
        db      0feh
        db      3fh
        db      0fch
        db      1fh
        db      0f8h
        db      20h
        db      04h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      2fh
        db      00h
        db      3eh
        db      81h
        db      5dh
        db      0e2h
        db      0f6h
        db      0dch
        db      31h
        db      80h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0f4h
        db      81h
        db      7ch
        db      47h
        db      0bah
        db      3bh
        db      6fh
        db      01h
        db      8ch
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0fh
        db      3eh
        db      7fh
        db      7eh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      70h
        db      0c0h
        db      00h
        db      80h
        db      0fh
        db      3eh
        db      7fh
        db      7eh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      70h
        db      0c0h
        db      00h
        db      80h
        db      00h
        db      00h
        db      00h
        db      0f0h
        db      07h
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0eh
        db      78h
        db      00h
        db      00h
        db      0f0h
        db      07h
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0feh
        db      7fh
        db      0eh
        db      78h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      03h
        db      0c0h
        db      07h
        db      0f0h
        db      1fh
        db      0feh
        db      7fh
        db      0feh
        db      7eh
        db      0feh
        db      7ch
        db      3eh
        db      79h
        db      0eh
        db      63h
        db      0c0h
        db      07h
        db      0f0h
        db      1fh
        db      0feh
        db      7fh
        db      0feh
        db      7eh
        db      0feh
        db      7ch
        db      3eh
        db      78h
        db      0eh
        db      60h
        db      00h
        db      00h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      07h
        db      0e0h
        db      03h
        db      0c0h
        db      0fh
        db      0f0h
        db      19h
        db      98h
        db      1fh
        db      0f8h
        db      1fh
        db      0f8h
        db      0fh
        db      0f0h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      06h
        db      60h
        db      06h
        db      60h
        db      06h
        db      60h
        db      07h
        db      0e0h
        db      03h
        db      0c0h
        db      06h
        db      60h
        db      00h
        db      00h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      07h
        db      0e0h
        db      0bh
        db      0c0h
        db      0bh
        db      0c0h
        db      19h
        db      80h
        db      1fh
        db      0e0h
        db      1fh
        db      0f0h
        db      0fh
        db      0f0h
        db      07h
        db      0f0h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      06h
        db      60h
        db      07h
        db      60h
        db      03h
        db      60h
        db      06h
        db      0e0h
        db      00h
        db      0c0h
        db      00h
        db      60h
        db      00h
        db      00h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      07h
        db      0e0h
        db      03h
        db      0d0h
        db      03h
        db      0d0h
        db      01h
        db      98h
        db      07h
        db      0f8h
        db      0fh
        db      0f8h
        db      0fh
        db      0f0h
        db      0fh
        db      0e0h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      06h
        db      60h
        db      06h
        db      0e0h
        db      06h
        db      0c0h
        db      07h
        db      60h
        db      03h
        db      00h
        db      06h
        db      00h
        db      00h
        db      00h
        db      0ch
        db      1ah
        db      0ch
        db      0ch
        db      33h
        db      3dh
        db      3dh
        db      27h
        db      1fh
        db      12h
        db      0ch
        db      0ch
        db      0ch
        db      0ch
        db      0ch
        db      1eh
        db      0ch
        db      1ah
        db      0ch
        db      0ch
        db      33h
        db      7dh
        db      0ddh
        db      1fh
        db      1fh
        db      12h
        db      0ch
        db      0ch
        db      0ch
        db      0ch
        db      0ch
        db      1eh
        db      0ch
        db      1ah
        db      2ch
        db      4ch
        db      73h
        db      3dh
        db      1dh
        db      1fh
        db      1fh
        db      12h
        db      0ch
        db      0ch
        db      0ch
        db      0ch
        db      0ch
        db      1eh
        db      38h
        db      7ch
        db      38h
        db      38h
        db      10h
        db      38h
        db      6ch
        db      6ch
        db      6ch
        db      74h
        db      3ch
        db      28h
        db      28h
        db      28h
        db      28h
        db      34h
        db      38h
        db      7ch
        db      38h
        db      38h
        db      10h
        db      38h
        db      6ch
        db      6ch
        db      6ch
        db      74h
        db      3ch
        db      28h
        db      28h
        db      44h
        db      44h
        db      26h
        db      38h
        db      7ch
        db      38h
        db      38h
        db      10h
        db      38h
        db      6ch
        db      6ch
        db      6ch
        db      74h
        db      3ch
        db      28h
        db      44h
        db      44h
        db      82h
        db      43h
        db      1ch
        db      3eh
        db      1ch
        db      1ch
        db      08h
        db      1ch
        db      36h
        db      36h
        db      36h
        db      2eh
        db      3ch
        db      14h
        db      14h
        db      14h
        db      14h
        db      2ch
        db      1ch
        db      3eh
        db      1ch
        db      1ch
        db      08h
        db      1ch
        db      36h
        db      36h
        db      36h
        db      2eh
        db      3ch
        db      14h
        db      14h
        db      22h
        db      22h
        db      64h
        db      1ch
        db      3eh
        db      1ch
        db      1ch
        db      08h
        db      1ch
        db      36h
        db      36h
        db      36h
        db      2eh
        db      3ch
        db      14h
        db      22h
        db      22h
        db      41h
        db      0c2h
        db      00h
        db      00h
        db      0f0h
        db      00h
        db      60h
        db      00h
        db      7fh
        db      0fch
        db      35h
        db      52h
        db      3fh
        db      0ffh
        db      1fh
        db      0feh
        db      04h
        db      08h
        db      00h
        db      00h
        db      00h
        db      0fh
        db      00h
        db      06h
        db      3fh
        db      0feh
        db      4ah
        db      0ach
        db      0ffh
        db      0fch
        db      7fh
        db      0f8h
        db      10h
        db      20h
        db      00h
        db      00h
        db      00h
        db      00h
        db      1fh
        db      0ffh
        db      00h
        db      40h
        db      01h
        db      0f0h
        db      87h
        db      0cch
        db      0ffh
        db      0c2h
        db      3fh
        db      0ffh
        db      07h
        db      0feh
        db      01h
        db      09h
        db      07h
        db      0feh
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      03h
        db      0f8h
        db      00h
        db      40h
        db      01h
        db      0f0h
        db      87h
        db      0cch
        db      0ffh
        db      0c2h
        db      3fh
        db      0ffh
        db      07h
        db      0feh
        db      01h
        db      09h
        db      07h
        db      0feh
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      40h
        db      00h
        db      40h
        db      01h
        db      0f0h
        db      87h
        db      0cch
        db      0ffh
        db      0c2h
        db      3fh
        db      0ffh
        db      07h
        db      0feh
        db      01h
        db      09h
        db      07h
        db      0feh
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0ffh
        db      0f8h
        db      02h
        db      00h
        db      0fh
        db      80h
        db      33h
        db      0e1h
        db      43h
        db      0ffh
        db      0ffh
        db      0fch
        db      7fh
        db      0e0h
        db      90h
        db      80h
        db      7fh
        db      0e0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      1fh
        db      0c0h
        db      02h
        db      00h
        db      0fh
        db      80h
        db      33h
        db      0e1h
        db      43h
        db      0ffh
        db      0ffh
        db      0fch
        db      7fh
        db      0e0h
        db      90h
        db      80h
        db      7fh
        db      0e0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      02h
        db      00h
        db      02h
        db      00h
        db      0fh
        db      80h
        db      33h
        db      0e1h
        db      43h
        db      0ffh
        db      0ffh
        db      0fch
        db      7fh
        db      0e0h
        db      90h
        db      80h
        db      7fh
        db      0e0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      03h
        db      80h
        db      03h
        db      80h
        db      07h
        db      0c0h
        db      02h
        db      80h
        db      03h
        db      0c0h
        db      03h
        db      80h
        db      01h
        db      00h
        db      03h
        db      80h
        db      17h
        db      0c0h
        db      37h
        db      0c0h
        db      0eh
        db      0e0h
        db      0dh
        db      0e0h
        db      03h
        db      80h
        db      05h
        db      0c0h
        db      06h
        db      0c0h
        db      04h
        db      60h
        db      03h
        db      80h
        db      03h
        db      80h
        db      07h
        db      0c0h
        db      02h
        db      80h
        db      03h
        db      0c0h
        db      03h
        db      80h
        db      01h
        db      00h
        db      03h
        db      80h
        db      06h
        db      0c0h
        db      06h
        db      0c0h
        db      16h
        db      0d0h
        db      0ch
        db      60h
        db      12h
        db      90h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      80h
        db      03h
        db      80h
        db      03h
        db      80h
        db      07h
        db      0c0h
        db      02h
        db      80h
        db      03h
        db      0c0h
        db      03h
        db      80h
        db      01h
        db      00h
        db      03h
        db      90h
        db      07h
        db      0d8h
        db      07h
        db      0e0h
        db      0eh
        db      0e0h
        db      0fh
        db      60h
        db      03h
        db      80h
        db      07h
        db      40h
        db      06h
        db      0c0h
        db      07h
        db      60h
        db      01h
        db      0c0h
        db      01h
        db      0c0h
        db      03h
        db      0e0h
        db      01h
        db      40h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      00h
        db      80h
        db      01h
        db      0c0h
        db      03h
        db      0e8h
        db      03h
        db      0ech
        db      07h
        db      70h
        db      07h
        db      0b0h
        db      01h
        db      0c0h
        db      03h
        db      0a0h
        db      03h
        db      60h
        db      06h
        db      20h
        db      01h
        db      0c0h
        db      01h
        db      0c0h
        db      03h
        db      0e0h
        db      01h
        db      40h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      00h
        db      80h
        db      01h
        db      0c0h
        db      03h
        db      60h
        db      03h
        db      60h
        db      0bh
        db      68h
        db      06h
        db      30h
        db      09h
        db      48h
        db      00h
        db      80h
        db      00h
        db      80h
        db      01h
        db      80h
        db      01h
        db      0c0h
        db      01h
        db      0c0h
        db      03h
        db      0e0h
        db      01h
        db      40h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      00h
        db      80h
        db      09h
        db      0c0h
        db      1bh
        db      0e0h
        db      07h
        db      0e0h
        db      07h
        db      70h
        db      06h
        db      0f0h
        db      01h
        db      0c0h
        db      02h
        db      0e0h
        db      03h
        db      60h
        db      06h
        db      0e0h
        db      01h
        db      00h
        db      02h
        db      80h
        db      07h
        db      0c0h
        db      0eh
        db      0e0h
        db      1fh
        db      0f0h
        db      3eh
        db      0f8h
        db      7fh
        db      0fch
        db      92h
        db      92h
        db      7fh
        db      0fch
        db      3eh
        db      0f8h
        db      1fh
        db      0f0h
        db      0eh
        db      0e0h
        db      07h
        db      0c0h
        db      02h
        db      80h
        db      01h
        db      00h
        db      00h
        db      00h
        db      01h
        db      00h
        db      02h
        db      80h
        db      03h
        db      80h
        db      06h
        db      0c0h
        db      07h
        db      0c0h
        db      0eh
        db      0e0h
        db      0fh
        db      0e0h
        db      1ah
        db      0b0h
        db      0fh
        db      0e0h
        db      0eh
        db      0e0h
        db      07h
        db      0c0h
        db      06h
        db      0c0h
        db      03h
        db      80h
        db      02h
        db      80h
        db      01h
        db      00h
        db      00h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      01h
        db      00h
        db      00h
        db      00h
        db      3ch
        db      7eh
        db      0c3h
        db      0ffh
        db      7eh
        db      2ch
        db      2ch
        db      5eh
        db      0bbh
        db      0bfh
        db      0bdh
        db      0bfh
        db      0bdh
        db      0ffh
        db      7ah
        db      7ah
        db      0fdh
        db      0bdh
        db      0fdh
        db      0fdh
        db      0fdh
        db      0bdh
        db      0fah
        db      7ch
        db      44h
        db      92h
        db      92h
        db      92h
        db      44h
        db      28h
        db      10h
        db      10h
        db      03h
        db      0c0h
        db      04h
        db      20h
        db      03h
        db      0c0h
        db      01h
        db      80h
        db      07h
        db      0e0h
        db      0fh
        db      0f0h
        db      1ah
        db      0d8h
        db      33h
        db      0cch
        db      53h
        db      4ah
        db      03h
        db      0c0h
        db      02h
        db      0c0h
        db      01h
        db      80h
        db      01h
        db      80h
        db      03h
        db      0c0h
        db      07h
        db      0e0h
        db      02h
        db      40h
        db      00h
        db      00h
        db      00h
        db      0eh
        db      00h
        db      7fh
        db      00h
        db      0eh
        db      00h
        db      06h
        db      18h
        db      0ch
        db      27h
        db      0fah
        db      0ffh
        db      0c5h
        db      27h
        db      0fah
        db      18h
        db      0ch
        db      00h
        db      06h
        db      00h
        db      0eh
        db      00h
        db      7fh
        db      00h
        db      0eh
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0feh
        db      00h
        db      0f8h
        db      00h
        db      3ch
        db      00h
        db      7fh
        db      0f8h
        db      0c7h
        db      44h
        db      0d5h
        db      42h
        db      0c7h
        db      7fh
        db      0ffh
        db      0feh
        db      3fh
        db      0f8h
        db      08h
        db      22h
        db      3fh
        db      0fch
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      40h
        db      00h
        db      0e0h
        db      00h
        db      0e0h
        db      00h
        db      40h
        db      00h
        db      0e0h
        db      00h
        db      0a0h
        db      03h
        db      20h
        db      06h
        db      0ffh
        db      0ch
        db      0dfh
        db      0ch
        db      0c6h
        db      3ch
        db      0ceh
        db      69h
        db      0dah
        db      0cfh
        db      0fah
        db      0efh
        db      0f4h
        db      7fh
        db      0f8h
        db      01h
        db      0c0h
        db      06h
        db      80h
        db      0bh
        db      80h
        db      17h
        db      00h
        db      17h
        db      10h
        db      2fh
        db      20h
        db      2fh
        db      0c0h
        db      2fh
        db      80h
        db      3fh
        db      0c0h
        db      1fh
        db      0e0h
        db      1fh
        db      0f8h
        db      0fh
        db      0f0h
        db      03h
        db      0c0h
        db      01h
        db      00h
        db      07h
        db      0c0h
        db      07h
        db      0c0h
        db      03h
        db      80h
        db      01h
        db      60h
        db      01h
        db      0d0h
        db      00h
        db      0e8h
        db      08h
        db      0e8h
        db      04h
        db      0f4h
        db      03h
        db      0f4h
        db      01h
        db      0f4h
        db      03h
        db      0fch
        db      07h
        db      0f8h
        db      1fh
        db      0f8h
        db      0fh
        db      0f0h
        db      03h
        db      0c0h
        db      01h
        db      00h
        db      07h
        db      0c0h
        db      07h
        db      0c0h
        db      03h
        db      80h
        db      04h
        db      40h
        db      09h
        db      20h
        db      11h
        db      10h
        db      11h
        db      10h
        db      21h
        db      08h
        db      30h
        db      18h
        db      30h
        db      18h
        db      38h
        db      38h
        db      1fh
        db      0f0h
        db      1fh
        db      0f0h
        db      0fh
        db      0e0h
        db      07h
        db      0c0h
        db      01h
        db      00h
        db      07h
        db      0c0h
        db      07h
        db      0c0h
        db      03h
        db      80h
        db      07h
        db      0c0h
        db      0dh
        db      0e0h
        db      1bh
        db      0f0h
        db      17h
        db      0f0h
        db      37h
        db      0f8h
        db      3fh
        db      0f8h
        db      37h
        db      0d8h
        db      3fh
        db      0f8h
        db      1fh
        db      0d0h
        db      1fh
        db      0b0h
        db      0eh
        db      60h
        db      07h
        db      0c0h
        db      01h
        db      00h
        db      07h
        db      0c0h
        db      07h
        db      0c0h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      01h
        db      0c3h
        db      0e0h
        db      97h
        db      0ffh
        db      0f8h
        db      4fh
        db      0ffh
        db      0fch
        db      7bh
        db      0ffh
        db      0feh
        db      2fh
        db      0ffh
        db      0feh
        db      1fh
        db      0f7h
        db      0feh
        db      07h
        db      7ah
        db      0feh
        db      00h
        db      0bah
        db      0fch
        db      00h
        db      0bdh
        db      7ch
        db      01h
        db      70h
        db      0b8h
        db      01h
        db      70h
        db      0b8h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      93h
        db      0c3h
        db      0e0h
        db      4fh
        db      0ffh
        db      0f8h
        db      7bh
        db      0ffh
        db      0fch
        db      2fh
        db      0ffh
        db      0feh
        db      1fh
        db      0ffh
        db      0feh
        db      07h
        db      0f7h
        db      0feh
        db      01h
        db      7ah
        db      0feh
        db      00h
        db      0bah
        db      0fch
        db      00h
        db      0bdh
        db      7ch
        db      01h
        db      70h
        db      0b8h
        db      01h
        db      70h
        db      0b8h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      00h
        db      0e3h
        db      0e0h
        db      03h
        db      0ffh
        db      0f8h
        db      97h
        db      0ffh
        db      0fch
        db      4fh
        db      0ffh
        db      0feh
        db      7bh
        db      0ffh
        db      0feh
        db      2fh
        db      0f7h
        db      0feh
        db      1fh
        db      7ah
        db      0feh
        db      06h
        db      0bah
        db      0fch
        db      00h
        db      0bdh
        db      7ch
        db      01h
        db      70h
        db      0b8h
        db      01h
        db      70h
        db      0b8h
        db      07h
        db      0e0h
        db      1ch
        db      38h
        db      33h
        db      0cch
        db      6fh
        db      0b6h
        db      5fh
        db      0eah
        db      0dfh
        db      0fbh
        db      0b5h
        db      0adh
        db      0bbh
        db      0ddh
        db      0b5h
        db      0adh
        db      0bfh
        db      0fdh
        db      0d7h
        db      0fbh
        db      5fh
        db      0fah
        db      6dh
        db      0b6h
        db      32h
        db      4ch
        db      1ch
        db      18h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      1ch
        db      38h
        db      32h
        db      4ch
        db      6dh
        db      0b6h
        db      5fh
        db      0fah
        db      0dfh
        db      0ebh
        db      0bfh
        db      0fdh
        db      0b5h
        db      0adh
        db      0bbh
        db      0ddh
        db      0b5h
        db      0adh
        db      0dfh
        db      0fbh
        db      57h
        db      0fah
        db      6dh
        db      0f6h
        db      33h
        db      0cch
        db      1ch
        db      38h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      1ch
        db      38h
        db      33h
        db      0cch
        db      6fh
        db      0f6h
        db      5ah
        db      0bah
        db      0dfh
        db      7bh
        db      0aeh
        db      0bdh
        db      9fh
        db      0fdh
        db      9fh
        db      0fdh
        db      0aeh
        db      0b5h
        db      0dfh
        db      7bh
        db      5eh
        db      0aah
        db      6fh
        db      0f6h
        db      33h
        db      0cch
        db      1ch
        db      38h
        db      07h
        db      0e0h
        db      07h
        db      0e0h
        db      1ch
        db      38h
        db      33h
        db      0cch
        db      6fh
        db      0f6h
        db      55h
        db      7ah
        db      0deh
        db      0fbh
        db      0adh
        db      75h
        db      0bfh
        db      0f9h
        db      0bfh
        db      0f9h
        db      0bdh
        db      75h
        db      0deh
        db      0fbh
        db      5dh
        db      5ah
        db      6fh
        db      0f6h
        db      33h
        db      0cch
        db      1ch
        db      38h
        db      07h
        db      0e0h
        db      00h
        db      38h
        db      07h
        db      30h
        db      0fh
        db      0b8h
        db      0fh
        db      0b8h
        db      1fh
        db      70h
        db      1fh
        db      0d8h
        db      1fh
        db      58h
        db      1fh
        db      0b8h
        db      0fh
        db      0b0h
        db      0eh
        db      0d0h
        db      06h
        db      0e0h
        db      06h
        db      0e0h
        db      07h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      80h
        db      03h
        db      0c0h
        db      00h
        db      38h
        db      01h
        db      30h
        db      03h
        db      0b8h
        db      03h
        db      0b8h
        db      07h
        db      70h
        db      07h
        db      0d8h
        db      07h
        db      58h
        db      07h
        db      0b8h
        db      07h
        db      0b0h
        db      06h
        db      0d0h
        db      06h
        db      0e0h
        db      02h
        db      0e0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      80h
        db      03h
        db      0c0h
        db      00h
        db      38h
        db      00h
        db      30h
        db      00h
        db      38h
        db      00h
        db      0b8h
        db      01h
        db      0f0h
        db      01h
        db      0d8h
        db      01h
        db      0d8h
        db      03h
        db      0f8h
        db      03h
        db      0f0h
        db      03h
        db      0d0h
        db      02h
        db      0e0h
        db      03h
        db      0e0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      80h
        db      03h
        db      0c0h
        db      1ch
        db      00h
        db      0ch
        db      0e0h
        db      1dh
        db      0f0h
        db      1dh
        db      0f0h
        db      0eh
        db      0f8h
        db      1bh
        db      0f8h
        db      1ah
        db      0f8h
        db      1dh
        db      0f8h
        db      0dh
        db      0f0h
        db      0bh
        db      70h
        db      07h
        db      60h
        db      07h
        db      60h
        db      03h
        db      0e0h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      03h
        db      0c0h
        db      1ch
        db      00h
        db      0ch
        db      80h
        db      1dh
        db      0c0h
        db      1dh
        db      0c0h
        db      0eh
        db      0e0h
        db      1bh
        db      0e0h
        db      1ah
        db      0e0h
        db      1dh
        db      0e0h
        db      0dh
        db      0e0h
        db      0bh
        db      60h
        db      07h
        db      60h
        db      07h
        db      40h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      03h
        db      0c0h
        db      1ch
        db      00h
        db      0ch
        db      00h
        db      1ch
        db      00h
        db      1dh
        db      00h
        db      0fh
        db      80h
        db      1bh
        db      80h
        db      1bh
        db      80h
        db      1fh
        db      0c0h
        db      0fh
        db      0c0h
        db      0bh
        db      0c0h
        db      07h
        db      40h
        db      07h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      01h
        db      80h
        db      07h
        db      0c0h
        db      0fh
        db      0c0h
        db      0fh
        db      80h
        db      0eh
        db      0c0h
        db      0eh
        db      0c0h
        db      0eh
        db      0c0h
        db      0eh
        db      0c0h
        db      0fh
        db      0c0h
        db      0fh
        db      80h
        db      0bh
        db      80h
        db      07h
        db      80h
        db      03h
        db      80h
        db      03h
        db      80h
        db      03h
        db      0c0h
        db      01h
        db      0c0h
        db      01h
        db      80h
        db      0dh
        db      0c0h
        db      0fh
        db      0c0h
        db      0fh
        db      80h
        db      1eh
        db      0c0h
        db      1eh
        db      0c0h
        db      1eh
        db      0c0h
        db      1eh
        db      0c0h
        db      1fh
        db      0c0h
        db      0dh
        db      80h
        db      0dh
        db      0c0h
        db      0bh
        db      0c0h
        db      03h
        db      40h
        db      02h
        db      60h
        db      03h
        db      60h
        db      01h
        db      0c0h
        db      01h
        db      80h
        db      0dh
        db      0c0h
        db      1fh
        db      0c0h
        db      1fh
        db      80h
        db      0eh
        db      0c0h
        db      1eh
        db      0c0h
        db      1eh
        db      0c0h
        db      1eh
        db      0c0h
        db      0fh
        db      0c0h
        db      0dh
        db      80h
        db      0dh
        db      0c0h
        db      0ah
        db      0c0h
        db      02h
        db      0c0h
        db      02h
        db      0c0h
        db      03h
        db      60h
        db      03h
        db      80h
        db      01h
        db      80h
        db      03h
        db      0e0h
        db      03h
        db      0f0h
        db      01h
        db      0f0h
        db      03h
        db      70h
        db      03h
        db      70h
        db      03h
        db      70h
        db      03h
        db      70h
        db      03h
        db      0f0h
        db      01h
        db      0f0h
        db      01h
        db      0d0h
        db      01h
        db      0e0h
        db      01h
        db      0c0h
        db      01h
        db      0c0h
        db      03h
        db      0c0h
        db      03h
        db      80h
        db      01h
        db      80h
        db      03h
        db      0b0h
        db      03h
        db      0f0h
        db      01h
        db      0f0h
        db      03h
        db      78h
        db      03h
        db      78h
        db      03h
        db      78h
        db      03h
        db      78h
        db      03h
        db      0f8h
        db      01h
        db      0b0h
        db      03h
        db      0b0h
        db      03h
        db      0d0h
        db      02h
        db      0c0h
        db      06h
        db      40h
        db      06h
        db      0c0h
        db      03h
        db      80h
        db      01h
        db      80h
        db      03h
        db      0b0h
        db      03h
        db      0f8h
        db      01h
        db      0f8h
        db      03h
        db      70h
        db      03h
        db      78h
        db      03h
        db      78h
        db      03h
        db      78h
        db      03h
        db      0f0h
        db      01h
        db      0b0h
        db      03h
        db      0b0h
        db      03h
        db      50h
        db      03h
        db      40h
        db      03h
        db      40h
        db      06h
        db      0c0h
